name: Android APK Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3-dev \
            python3-pip \
            openjdk-11-jdk \
            unzip \
            libffi-dev \
            libssl-dev \
            git \
            zip \
            zlib1g-dev

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      # Step 4: Install Buildozer
      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.33

      # Step 5: Ensure build directory exists
      - name: Ensure Build Directory
        run: |
          if [ ! -f buildozer.spec ]; then
            echo "buildozer.spec not found!"
            exit 1
          fi

      # Step 6: Build APK
      - name: Build APK
        run: |
          buildozer -v android debug

      # Step 7: Upload the APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AirMouse-APK
          path: bin/*.apk
