name: Build APK with Buildozer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Cache dependencies
      - name: Cache Buildozer
        uses: actions/cache@v3
        with:
          path: ~/.buildozer
          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            libssl-dev \
            libffi-dev \
            python3-dev \
            python3-venv \
            zip \
            unzip \
            default-jdk \
            adb
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install buildozer cython==0.29.33

      # Step 4: Build APK
      - name: Build APK
        run: |
          . venv/bin/activate
          buildozer -v android debug
          mkdir -p build_output
          mv bin/*.apk build_output/

      # Step 5: Upload APK as Artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AirMouse-APK
          path: build_output/*.apk
